### ISSUE TITLE
UrlCacheAppHelper not found

### ISSUE THREAD

**Issue by sneakersgames** [ProLoser/BakingPlate#12]
I did a fresh install and followed the setup guide and have this problem:

Fatal error: Class 'UrlCacheAppHelper' not found in /Applications/MAMP/htdocs/cakephp/app/app_helper.php on line 24

**Comment by ProLoser** [comment]
Sorry about that, I was having some problems with this helper so I removed it.

To add the plugin run: `cake plate add url_cache`

Or just delete line 24 if you don't want it. It was giving me this weird behavior where all my links are actually links from the previous page (like the cache was lagging or something). If it works fine for you please let me know
