### ISSUE TITLE
submodules don't get added

### ISSUE THREAD

**Issue by sams** [ProLoser/BakingPlate#17]
- I can't add submodule via number
- baking projects with `plate bake MyProject` just does not add any submodules (plate is looking for a group named MyProject) nor does it when baking and typing in the path of project when prompted
- setting the path of submodules with DS menas that windows with have \  within the .gitmodules file and that will cause issue when `git submodule update --init`
- passthru git init has to happen before db confg - otherwise the project will not get initialized and submodules will not be made 

Still looking at whats up - it looks like the group is set to the name of project before the submodules are added
## 

Just pushed some commits that resolve the above - I have also enabled
`plate add all -g proloser`

**Comment by ProLoser** [comment]
I had this fixed before the merge, let me take a look at it tonight and fix
it. The reason is that I don't want to break or change the rest of the
functionality of the shell and it should be a simple fix.
On Dec 19, 2011 1:09 PM, "Sam Sherlock" <
reply@reply.github.com>
wrote:

**Comment by sams** [comment]
phah github missed my mention of the issue #17

The commits are simple
https://github.com/sams/BakingPlate/tree/issue17
