### ISSUE TITLE
PlateComponent: $this->request not defined

### ISSUE THREAD

**Issue by sdd** [ProLoser/BakingPlate#18]
Hi ProLoser/Sams,

I ran into an issue when trying to use PlateComponent - I was getting an error telling me that $this->request was not defined in _checkSSL(). I have forked and uploaded my change - but I'm guessing that this problem may be down to my unfamiliarity with 2.0.

**Comment by ProLoser** [comment]
Should be $this->controller -> request. 

We're still catching all the 2.0 bugs

**Comment by ProLoser** [comment]
This has already been fixed on my latest version. I recommend rolling back your commit.

[Refer to](https://github.com/ProLoser/BakingPlate/commit/134130f916e71b0e739e71fa08c553b1c6edd0c4#L38L106)
