### ISSUE TITLE
Problem with git

### ISSUE THREAD

**Issue by byqsri** [ProLoser/BakingPlate#20]
Hi
When i try to clone the plugin in my app from git I get this error 
"The remote end hung up unexpectedly"
With other repository all works fine so I think that there isn't an error in my git client 
Many thanks

**Comment by ProLoser** [comment]
It sounds like you're not issuing the command in git properly, or the url you're using is wrong. Can you copy-paste the line code you're using in console?

**Comment by byqsri** [comment]
yes ,yes
you is right
sorry
Many Thanks

2012/2/17 Dean Sofer
reply@reply.github.com:
