### ISSUE TITLE
Personal Config submodules

### ISSUE THREAD

**Issue by sams** [ProLoser/BakingPlate#21]
The docs don't show how to load additional submodules

I found that -c personalmodules does not load anything with browse

I may be doing it wrong - I made some tweaks adding the option to the browserParams (then the -c is shown in help)
but I also needed add other stuff too and this seems to be working

would be great if you could clarify this :)

**Comment by ProLoser** [comment]
Who's fourth ate you using?

Sam Sherlock reply@reply.github.com
wrote:

The docs don't show how to load additional submodules

I found that -c personalmodules does not load anything with browse

I may be doing it wrong - I made some tweaks adding the option to the
browserParams (then the -c is shown in help)
but I also needed add other stuff too and this seems to be working

would be great if you could clarify this :)

---

Reply to this email directly or view it on GitHub:
https://github.com/ProLoser/BakingPlate/issues/21
