### ISSUE TITLE
plate console search needs updating

### ISSUE THREAD

**Issue by sams** [ProLoser/BakingPlate#22]
cakepackages has moved to plugins.cakephp.org - yay!

so the search command needs updating to work again.

**Comment by ProLoser** [comment]
What is the the JSON url? I haven't seen their new source code.

**Comment by sams** [comment]
using http://api.cakepackages.com/ makes the search work

perhaps api access is not yet working on plugins.cakephp.org

**Comment by ProLoser** [comment]
This is resolved in your pull request right? If so can you close this?
