### ISSUE TITLE
Setup trouble

### ISSUE THREAD

**Issue by alscheuring** [ProLoser/BakingPlate#24]
Hello,
I've done a new install of 2.1.1, set up the database, cipher, seed ,etc.
I've pulled from git into the 'plugin' folder on the top level of the install (not app/Plugin). So it's plugin/BakingPlate.
From app I tried to run './Console cake plate' and I get the following:

Error: Shell class PlateShell could not be found.
#0 /var/www/platetest2/lib/Cake/Console/ShellDispatcher.php(167): ShellDispatcher->_getShell('plate')
#1 /var/www/platetest2/lib/Cake/Console/ShellDispatcher.php(69): ShellDispatcher->dispatch()
#2 /var/www/platetest2/app/Console/cake.php(33): ShellDispatcher::run(Array)
#3 {main}

Can you help me out? What did I miss?

**Comment by ProLoser** [comment]
So (annoyingly) you have to refer to plugin shells with plugin syntax now.

Running `cake BakingPlate.plate` should work. Additionally, the plugin us
supposed to make creating a new project easier too.  If the documentation
is wrong feel free to submit a fix with my note.

I wish I could find a way to make the command easier.
On Apr 25, 2012 6:35 PM, "alscheuring" <
reply@reply.github.com>
wrote:

**Comment by alscheuring** [comment]
Ah thank you. That's the stuff.

On 4/25/12 10:28 PM, Dean Sofer wrote:

> So (annoyingly) you have to refer to plugin shells with plugin syntax now.
> 
> Running `cake BakingPlate.plate` should work. Additionally, the plugin us
> supposed to make creating a new project easier too.  If the documentation
> is wrong feel free to submit a fix with my note.
> 
> I wish I could find a way to make the command easier.
> On Apr 25, 2012 6:35 PM, "alscheuring"<
> reply@reply.github.com>
> wrote:
> 
> > Hello,
> > I've done a new install of 2.1.1, set up the database, cipher, seed ,etc.
> > I've pulled from git into the 'plugin' folder on the top level of the
> > install (not app/Plugin). So it's plugin/BakingPlate.
> >  From app I tried to run './Console cake plate' and I get the following:
> > 
> > Error: Shell class PlateShell could not be found.
> > #0 /var/www/platetest2/lib/Cake/Console/ShellDispatcher.php(167):
> > ShellDispatcher->_getShell('plate')
> > #1 /var/www/platetest2/lib/Cake/Console/ShellDispatcher.php(69):
> > ShellDispatcher->dispatch()
> > #2 /var/www/platetest2/app/Console/cake.php(33):
> > ShellDispatcher::run(Array)
> > #3 {main}
> > 
> > Can you help me out? What did I miss?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ProLoser/BakingPlate/issues/24
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ProLoser/BakingPlate/issues/24#issuecomment-5348290

## 

Al Scheuring
Systems Administrator
Department of Biological Sciences
Carnegie Mellon University
