### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by poppan** [ProLoser/BakingPlate#27]
Hi, i encountered a problem during install.

fresh install cake 2.1.3 => /var/www/cakephp2.1.3

per instructions @ https://github.com/ProLoser/BakingPlate/wiki/Setup

in /var/www/cakephp2.1.3 > git clone git://github.com/ProLoser/BakingPlate.git plugins/BakingPlate

in /var/www/cakephp2.1.3/app > ./Console/cake baking_plate.plate
Error: Plugin BakingPlate could not be found.
#0 /var/www/cakephp/lib/Cake/Core/App.php(364): CakePlugin::path('BakingPlate')
#1 /var/www/cakephp/lib/Cake/Core/App.php(225): App::pluginPath('BakingPlate')
#2 /var/www/cakephp/lib/Cake/Core/App.php(542): App::path('Console/Command', 'BakingPlate')
#3 [internal function]: App::load('PlateShell')
#4 [internal function]: spl_autoload_call('PlateShell')
#5 /var/www/cakephp/lib/Cake/Console/ShellDispatcher.php(216): class_exists('PlateShell')
#6 /var/www/cakephp/lib/Cake/Console/ShellDispatcher.php(167): ShellDispatcher->_getShell('baking_plate.pl...')
#7 /var/www/cakephp/lib/Cake/Console/ShellDispatcher.php(69): ShellDispatcher->dispatch()
#8 /var/www/cakephp/app/Console/cake.php(33): ShellDispatcher::run(Array)
#9 {main}

in /var/www/cakephp2.1.3/app > ./Console/cake BakingPlate.plate
Error: Plugin BakingPlate could not be found.
#0 /var/www/cakephp/lib/Cake/Core/App.php(364): CakePlugin::path('BakingPlate')
#1 /var/www/cakephp/lib/Cake/Core/App.php(225): App::pluginPath('BakingPlate')
#2 /var/www/cakephp/lib/Cake/Core/App.php(542): App::path('Console/Command', 'BakingPlate')
#3 [internal function]: App::load('PlateShell')
#4 [internal function]: spl_autoload_call('PlateShell')
#5 /var/www/cakephp/lib/Cake/Console/ShellDispatcher.php(216): class_exists('PlateShell')
#6 /var/www/cakephp/lib/Cake/Console/ShellDispatcher.php(167): ShellDispatcher->_getShell('baking_plate.pl...')
#7 /var/www/cakephp/lib/Cake/Console/ShellDispatcher.php(69): ShellDispatcher->dispatch()
#8 /var/www/cakephp/app/Console/cake.php(33): ShellDispatcher::run(Array)
#9 {main}

i didn't even tried the third step : "./Console/cake cake baking_plate.plate bake [PROJECT_PATH]" as it doesn't seems valid ("cake" is called twice)

Is there something wrong with my install?

**Comment by ProLoser** [comment]
No sorry about that, the syntax for the other two steps was not updated to 2.0 fixing now.

**Comment by ProLoser** [comment]
If you refer to the docs again, I changed it. The 2.x syntax is `cake BakingPlate.plate ...`

I have been a bit annoyed with this syntax lately though and have considered renaming the project to CakePlate just so you can do `Plate.plate`.

Let me know if you have any other issues.

**Comment by poppan** [comment]
Thx for the quick reply.
I did try both commands :) neither worked at the time.

But then it kind of occured to me that cake2.x defaults to not loading plugins, after a simple loadAll() it now work.
In fact, both commands plugins syntax worked **cake BakingPlate.plate** & **cake baking_plate.plate**

This would be a simple addition to the wiki :

> edit /app/Config/bootstrap.php and add "CakePlugin::loadAll();"

also

> "./Console/cake cake BakingPlate.plate bake [PROJECT_PATH]" 

should be changed to 

> "./Console/cake BakingPlate.plate bake [PROJECT_PATH]"

Keep up the good work!

**Comment by ProLoser** [comment]
Ah my bad, if you want you can add the instructions yourself to the wiki. I'm currently driving right now
